#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt prompt_subst interactive_comments

eval "$(jump shell)"

alias man='tldr'
alias cat='bat'
alias ls='eza'
alias ll='eza -l'
alias f='fzf --preview "bat --color \"always\" {}"'
alias top='glances'
eval $(thefuck --alias)
alias fu='fuck'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Custom scripts in home
export USER_APPS="$HOME/Applications"
export PATH="$HOME/bin:$PATH"

# Homebrew
export PATH="/usr/local/bin:/usr/local/sbin:${PATH}"
export HOMEBREW_OPT="/opt/homebrew/opt"

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# R
export PATH="/opt/R/arm64/bin:${PATH}"

# Java
export JAVA_HOME="$HOMEBREW_OPT/openjdk@11/"
export PATH="$JAVA_HOME:$PATH"

# Python
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Flutter
export PATH="$PATH:$USER_APPS/flutter/bin"

# Google Cloud CLI
source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"
